name: CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'  # Detecta etiquetas con formato v1.0.0, v2.1.0, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Build Docker Scout Plugin
      run: go build -o docker-scout-plugin

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: docker-scout-plugin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
