  runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Checkout code
        uses: actions/checkout@v3  # Usamos v3 para asegurarnos de que sea la versión más reciente

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Cambia la versión si necesitas una diferente
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
        go-version: '1.20'  # Cambia la versión si necesitas una diferente

      - name: Verify Go installation
        run: go version  # Verifica que Go está instalado correctamente
      - name: Verify Go installation
        run: go version  # Verifica que Go está instalado correctamente

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor
      - name: Install dependencies
        run: |
         go mod tidy   # Esto descarga las dependencias necesarias
         go mod vendor # Si usas vendor, esto asegura que estén allí
      - name: Run tests
        run: go test ./...
      - name: Lint code
        run: go fmt ./...  # Formatea el código para mantenerlo consistente
        
      - name: Run tests
        run: go test ./... -v  # Ejecuta los tests y muestra el resultado de manera detallada
